root: true
env:  
  browser: false
  node: true
  es2022: true
extends: 
  - standard
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  semi: ["error", "always"]
  arrow-body-style: ["error", "as-needed"]
  indent: ["error", 4]
  newline-per-chained-call: ["error", { "ignoreChainWithDepth": 3 }]
  arrow-parens: ["error", "as-needed"]
  import/newline-after-import: ["error"]
  no-useless-constructor: 0
